import { TeamRole } from './role.enum';
import { PermissionFlagsBits } from './permissions.enum';

export const PermissionFlags: Record<TeamRole, PermissionFlagsBits[]> = {
  [TeamRole.TEAM_OWNER]: [
    PermissionFlagsBits.VIEW,
    PermissionFlagsBits.VIEW_ANALYTICS,
    PermissionFlagsBits.VIEW_INBOX,
    PermissionFlagsBits.VIEW_PLANNER,
    PermissionFlagsBits.VIEW_ADS,
    PermissionFlagsBits.SMARTLINKS,
    PermissionFlagsBits.EDIT,
    PermissionFlagsBits.REPORTS,
    PermissionFlagsBits.INBOX,
    PermissionFlagsBits.ADS,
    PermissionFlagsBits.HASHTAG_TRACKER,
    PermissionFlagsBits.PLANNER,
    PermissionFlagsBits.PLAN_AND_PUBLISH,
    PermissionFlagsBits.PLAN_PENDING_REVIEW,
    PermissionFlagsBits.REVIEW_POSTS,
    PermissionFlagsBits.MANAGEMENT,
    PermissionFlagsBits.BRAND,
  ],
  [TeamRole.MANAGER]: [
    PermissionFlagsBits.VIEW,
    PermissionFlagsBits.VIEW_ANALYTICS,
    PermissionFlagsBits.VIEW_INBOX,
    PermissionFlagsBits.VIEW_PLANNER,
    PermissionFlagsBits.VIEW_ADS,
    PermissionFlagsBits.SMARTLINKS,
    PermissionFlagsBits.EDIT,
    PermissionFlagsBits.REPORTS,
    PermissionFlagsBits.INBOX,
    PermissionFlagsBits.ADS,
    PermissionFlagsBits.HASHTAG_TRACKER,
    PermissionFlagsBits.PLANNER,
    PermissionFlagsBits.PLAN_AND_PUBLISH,
    PermissionFlagsBits.PLAN_PENDING_REVIEW,
    PermissionFlagsBits.REVIEW_POSTS,
    PermissionFlagsBits.MANAGEMENT,
    PermissionFlagsBits.BRAND,
  ],
  [TeamRole.EDITOR]: [
    PermissionFlagsBits.VIEW,
    PermissionFlagsBits.VIEW_ANALYTICS,
    PermissionFlagsBits.VIEW_INBOX,
    PermissionFlagsBits.VIEW_PLANNER,
    PermissionFlagsBits.VIEW_ADS,
    PermissionFlagsBits.SMARTLINKS,
    PermissionFlagsBits.EDIT,
    PermissionFlagsBits.REPORTS,
    PermissionFlagsBits.INBOX,
    PermissionFlagsBits.ADS,
    PermissionFlagsBits.HASHTAG_TRACKER,
    PermissionFlagsBits.PLANNER,
    PermissionFlagsBits.PLAN_AND_PUBLISH,
    PermissionFlagsBits.PLAN_PENDING_REVIEW,
    PermissionFlagsBits.REVIEW_POSTS,
  ],
  [TeamRole.CONTENT_CREATOR]: [
    PermissionFlagsBits.VIEW,
    PermissionFlagsBits.VIEW_ANALYTICS,
    PermissionFlagsBits.VIEW_INBOX,
    PermissionFlagsBits.VIEW_PLANNER,
    PermissionFlagsBits.VIEW_ADS,
    PermissionFlagsBits.SMARTLINKS,
    PermissionFlagsBits.REPORTS,
    PermissionFlagsBits.INBOX,
    PermissionFlagsBits.ADS,
    PermissionFlagsBits.HASHTAG_TRACKER,
    PermissionFlagsBits.PLAN_PENDING_REVIEW,
  ],
  [TeamRole.ANALYST]: [
    PermissionFlagsBits.VIEW,
    PermissionFlagsBits.VIEW_ANALYTICS,
    PermissionFlagsBits.VIEW_INBOX,
    PermissionFlagsBits.VIEW_PLANNER,
    PermissionFlagsBits.VIEW_ADS,
    PermissionFlagsBits.SMARTLINKS,
    PermissionFlagsBits.REPORTS,
  ],
  [TeamRole.CLIENT]: [
    PermissionFlagsBits.VIEW,
    PermissionFlagsBits.VIEW_ANALYTICS,
    PermissionFlagsBits.VIEW_INBOX,
    PermissionFlagsBits.VIEW_PLANNER,
    PermissionFlagsBits.VIEW_ADS,
    PermissionFlagsBits.SMARTLINKS,
    PermissionFlagsBits.REPORTS,
    PermissionFlagsBits.REVIEW_POSTS,
  ],
  [TeamRole.GUEST]: [
    PermissionFlagsBits.VIEW,
  ],
  [TeamRole.TEAM_MEMBER]: [
    PermissionFlagsBits.VIEW,
    PermissionFlagsBits.VIEW_ANALYTICS,
    PermissionFlagsBits.VIEW_INBOX,
    PermissionFlagsBits.VIEW_PLANNER,
    PermissionFlagsBits.VIEW_ADS,
    PermissionFlagsBits.SMARTLINKS,
    PermissionFlagsBits.INBOX,
    PermissionFlagsBits.ADS,
    PermissionFlagsBits.HASHTAG_TRACKER,
    PermissionFlagsBits.PLANNER,
  ],
};

