services:
  postgres:
    image: postgres:latest
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db
    restart: unless-stopped