services:
  postgres:
    image: postgres:latest
    container_name: psql
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
